### ISSUE TITLE
publish to pypi

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/j2lint#2]
Publishing to pypi would make consumption of this project easier.

**Comment by ryanmerolle** [comment]
As an FYI jinja2-lint & j2lint seemed to be somewhat used by:

- https://github.com/drm/jinja2-lint
- https://hub.docker.com/r/kaictl/j2lint

Not a huge deal, but just letting you know to prevent confusion since I assume people would want to use it in their CI with containers and such.

**Comment by carlbuchmann** [comment]
The initial release has been published to PyPI: https://pypi.org/project/j2lint/
