### ISSUE TITLE
jinja-statements-delimiter doesn't appear to be in the AVD docs

### ISSUE THREAD

**Issue by ollz272** [aristanetworks/j2lint#53]
We're getting errors from using `{%-` as delimiter in our jinja templates, which from i can understand is valid jinja. I've looked through the AVD docs and can't seem to find any errors relating to this error. Can someone provide some evidence, or maybe we can go ahead an remove this rule?

**Comment by gmuloc** [comment]
Hello, thanks for reaching out.
You are perfectly right that it is valid Jinja syntax - it is part of the core rules of this library as j2lint was created to serve the needs of AVD and we are relying on the ansible behavior (trim_blocks True / lstrip_blocks False - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#ansible-collections-ansible-builtin-template-module).

And as such we don't expect to have the `{%-` syntax in AVD for many of the templates. The AVD docs however do not mention this rule as you noticed..

We do use it in some places and in that case are using j2lint ignore feature as in https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_snapshot/templates/fabric_json_output.j2#L1:

```
{# j2lint: disable=jinja-statements-delimiter #}
```
You can decide to remove the rule for your own usage of course.

```
j2lint <FILES> -i jinja-statements-delimiter
```

(Be mindful of this issue with `-i` currently: https://github.com/aristanetworks/j2lint/issues/40)

**Comment by viktorkertesz** [comment]
I realized the same by using {%-. We have to use it because for example in Fortinet FMG trim_blocks is not enabled and we don't have influence on how templates are rendered. We'll use comment ignore. Thanks for the tips! Would be nice to have a config file :P

**Comment by gmuloc** [comment]
Thanks for the feedback @viktorkertesz - opened an issue to track this! I will close this issue for now.
