### ISSUE TITLE
leverage github releases

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/j2lint#9]
While there is no official pypi release, it would be nice to use the github release feature.  That way if users use proxy repo tools like nexus, they can download a tar of a specific release and install.

This is especially useful when these same users block github access direct access for cicd runners.

**Comment by carlbuchmann** [comment]
@ryanmerolle - we made the repo public to allow for broader testing and start the work to integrate into ansible-avd CI pipeline. We will maintain this codebase using SemVer and publish releases to GitHub similar to other repos the AVD maintains
We plan to release 1.0 once broader testing is complete!
